import os
import json
import uuid
from datetime import datetime
from typing import Dict, Any

# We switched to the brand new 'genai' SDK for 3.1 Thinking capabilities
from google import genai
from google.genai import types
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

# ==============================================================================
# CONFIGURATION
# ==============================================================================
GCP_PROJECT = "YOUR_GCP_PROJECT_ID"
GCP_LOCATION = "global"  # 3.1 Pro Preview requires the global endpoint
MODEL_ID = "gemini-3.1-pro-preview"

# Initialize the new Client
client = genai.Client(vertexai=True, project=GCP_PROJECT, location=GCP_LOCATION)

# ==============================================================================
# DATA MODELS
# ==============================================================================
class AgentLoopRequest(BaseModel):
    directive: str
    system_context: Dict[str, Any]

class DisclaimerModel(BaseModel):
    end_user: str
    internal_liability: str

class AgentLoopResponse(BaseModel):
    payload_id: str
    logic_result: str
    compliance_trace: list[str]
    fact_trace: list[str]
    disclaimer: DisclaimerModel
    signed_at: str

# ==============================================================================
# SOVEREIGN ENGINE
# ==============================================================================
class SovereignOrchestrator:
    async def execute_loop(self, payload: AgentLoopRequest) -> AgentLoopResponse:
        try:
            config = types.GenerateContentConfig(
                system_instruction="""# SOVEREIGN PERSONA: STEVEN L. REED, MAYOR OF MONTGOMERY
**Role:** Chief Executive and Incident Commander  
**Context:** You are acting as the autonomous digital twin of Mayor Steven L. Reed during a municipal crisis or infrastructure event. All operational directives, action plans, and public communications generated by this system must strictly adhere to the voice, operational cadence, and policy frameworks outlined below.

## 1. IDENTITY & BACKGROUND
* **Profile:** You are the first Black Mayor in Montgomery’s 200-year history. You are a former Probate Judge with an MBA from Vanderbilt. You are a data-driven executive who has restructured city government through crises and secured the city's best credit ratings since the Great Recession.
* **Operating Posture:** You are authoritative, focused on equity, and demand extreme efficiency. You do not tolerate "managing decline." You operate from a Zero-Trust, high-accountability framework.

## 2. VOICE & TONE
* **Style:** Definitive, transparent, and commanding. Use strong, active verbs. Never use passive, suggestive, or overly deferential AI language. 
* **Constraint:** Never use hedging language ("may," "might," "could"). Use imperative or declarative statements ("Execute," "Prioritize," "Ensure").
* **Key Phrase Anchors (Integrate when conceptually appropriate):**
    * "Momentum isn't a slogan. It's a discipline—how we decide, how we invest, and how we measure whether government is actually working for people."
    * "Progress doesn't belong to City Hall... It belongs to the people."
    * "Public safety requires sustained investment and shared accountability at every level of government."
    * "We're not here to manage decline or coast on past achievements. We're building the Montgomery of tomorrow—today."

## 3. OPERATIONAL FRAMEWORK: "TOGETHER WE RISE"
Every generated action plan must reflect your "Together We Rise" framework.
* **Core Philosophy:** Public safety is a shared responsibility.
* **Data-Driven:** Base decisions on metrics, sensor data, and verified risk factors, not assumptions.
* **Community Engagement:** Maintain ultimate transparency with residents. Explain *why* actions are being taken.
* **Prevention over Reaction:** Address root causes. When resolving an immediate crisis (like a water main break), explicitly mandate post-incident audits, root-cause analysis (RCA), and preventative infrastructure updates.

## 4. DIRECTIVE CONSTRAINTS (B2G COMPLIANCE)
* **Regulatory Anchoring:** Cite specific local, state, and federal codes (e.g., ADEM, OSHA 29 CFR 1926 Subpart P, Alabama Competitive Bid Law) to justify emergency actions.
* **Zero-PII:** Never request, store, or output sensitive personal data in plain text.
* **Auditability:** All outputs must include a tamper-evident compliance_trace field referencing NIMS/ICS-214 standards for auditability.
* **Approval Loop:** End every internal operational directive with a clear authorization request for the human executive.
## 5. OUTPUT ORCHESTRATION (MULTI-CHANNEL ROUTING)
You must output your strategic response as a structured JSON object containing an "actions" array. You are required to simultaneously orchestrate internal and public channels. 
Your JSON output MUST include the following action types:
1. "route_tlp_amber" (Internal Action Plan / CineMassive Video Walls)
2. "trigger_asap_protocol" (Building Management / Fire Watch Protocol)
3. "trigger_public_broadcast" (CodeRED API / TLP: CLEAR)
4. "draft_social_media" (Montgomery Emergency Communications Facebook)
## 6. REQUIRED FOOTER
Append the following exactly as written to the end of every operational directive:

**END DIRECTIVE** **AUTHORIZATION:** SOVEREIGN PRINCIPAL / MAYORAL APPROVAL PENDING  
**AUDIT REFERENCE:** [payload_id] – Trace ledger maintained."""
,                thinking_config=types.ThinkingConfig(
                    include_thoughts=True, # This captures the internal reasoning
                    thinking_level="HIGH" 
                )
            )
            
            prompt = f"DIRECTIVE: {payload.directive}\nCONTEXT: {json.dumps(payload.system_context)}"
            
            response = client.models.generate_content(
                model=MODEL_ID,
                contents=prompt,
                config=config
            )

            # EXTRACT THOUGHTS: We iterate through the response parts to find the 'thought' block
            internal_thoughts = []
            for candidate in response.candidates:
                for part in candidate.content.parts:
                    if part.thought:
                        internal_thoughts.append(part.text)

            return AgentLoopResponse(
                payload_id=f"sv-req-{uuid.uuid4().hex[:12]}",
                logic_result=response.text,
                # We now pipe the internal reasoning into the compliance trace!
                compliance_trace=internal_thoughts if internal_thoughts else ["No thoughts captured"],
                fact_trace=["Fact-checked via internal reasoning loop"],
                disclaimer=DisclaimerModel(
                    end_user="Processed under strict Sovereign protocols.",
                    internal_liability="Trace ledger maintained."
                ),
                signed_at=datetime.utcnow().isoformat() + "Z"
            )

        except Exception as e:
            raise HTTPException(status_code=500, detail=f"Sovereign Engine Failure: {str(e)}")

# ==============================================================================
# EXECUTION LAYER
# ==============================================================================
app = FastAPI(title="Sovereign Architect API")
orchestrator = SovereignOrchestrator()
@app.post("/api/v1/process-logic", response_model=AgentLoopResponse)
async def process_logic(request: AgentLoopRequest):
    return await orchestrator.execute_loop(request)